$ANSIBLE_VAULT;1.1;AES256
33356236343165313936326137636366353862663066653830616239636162366532616666613530
3737366261393465663262343436366633373730326363320a353063346365656563393961626230
64633435613435336233633139336231633032386230373731316566383363646431656434316365
6565336631376333350a306139313833663239343863396662346565376464386266366335393932
36356133663733653837333431373436626132323739366163666330303761313034
